# Generated by Django 4.1.7 on 2023-04-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffaccountprofile',
            name='district',
        ),
    ]
