# Generated by Django 4.1.7 on 2023-03-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_delete_userrole'),
        ('account', '0003_alter_account_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccountprofile',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='settings.district'),
            preserve_default=False,
        ),
    ]
