# Generated by Django 4.1.7 on 2023-03-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casesmodel',
            options={'verbose_name': 'Case', 'verbose_name_plural': 'Case List'},
        ),
        migrations.AlterField(
            model_name='casesmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('In_Process', 'In Process'), ('open', 'Open'), ('running', 'Running'), ('done', 'Done')], default='pending', max_length=255),
        ),
    ]
