# Generated by Django 4.1.7 on 2023-03-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalmodel',
            name='victim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='criminal.victim'),
            preserve_default=False,
        ),
    ]
