# Generated by Django 4.1.7 on 2023-03-22 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criminal', '0002_alter_casesmodel_options_alter_casesmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
