# Generated by Django 4.1.7 on 2023-03-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0002_criminalmodel_victim'),
    ]

    operations = [
        migrations.CreateModel(
            name='VictimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('documentType', models.CharField(choices=[('nid', 'National ID card'), ('passport', 'Passport'), ('driving licence', 'Driving Licence')], default='None', max_length=255)),
                ('document', models.ImageField(upload_to='criminal/victim/')),
                ('cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminal.casesmodel')),
            ],
            options={
                'verbose_name': 'Victim',
                'verbose_name_plural': 'Victim List',
            },
        ),
        migrations.RemoveField(
            model_name='criminalmodel',
            name='victim',
        ),
        migrations.DeleteModel(
            name='Victim',
        ),
    ]
