# Generated by Django 4.1.7 on 2023-03-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0003_victimmodel_remove_criminalmodel_victim_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PunishmentModel',
        ),
    ]
