# Generated by Django 4.1.7 on 2023-04-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criminal', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtModel',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('JudgeName', models.CharField(max_length=255)),
                ('CourtName', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Judge',
                'verbose_name_plural': 'Judge List',
            },
        ),
        migrations.CreateModel(
            name='PunishmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law.courtmodel')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminal.criminalmodel')),
                ('punishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.punishment')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.criminalstatus')),
            ],
            options={
                'verbose_name': 'Punishment',
                'verbose_name_plural': 'Punishment List',
                'db_table': 'CriminalPunishment',
            },
        ),
    ]
