# Generated by Django 4.1.7 on 2023-03-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courtmodel',
            options={'verbose_name': 'Court', 'verbose_name_plural': 'Court List'},
        ),
        migrations.AlterModelOptions(
            name='punishmentmodel',
            options={'verbose_name': 'Punishment', 'verbose_name_plural': 'Punishment List'},
        ),
    ]
