# Generated by Django 4.1.7 on 2023-04-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0002_alter_courtmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courtmodel',
            options={'verbose_name': 'Judge', 'verbose_name_plural': 'Judge List'},
        ),
    ]
