# Generated by Django 4.1.7 on 2023-04-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=55)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('cancel', 'Cancel'), ('done', 'Done')], default='pending', max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='report/file/')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Report List',
            },
        ),
        migrations.CreateModel(
            name='StationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stations/')),
                ('stationCode', models.CharField(max_length=255)),
                ('stationName', models.CharField(max_length=255, verbose_name='Station Name')),
                ('phone', models.CharField(max_length=255)),
                ('phone2', models.CharField(max_length=255, verbose_name='email')),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Station List',
            },
        ),
    ]
