# Generated by Django 4.1.7 on 2023-03-21 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 21, 21, 13, 50, 997513, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
