# Generated by Django 4.1.7 on 2023-03-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_reportmodel_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='email',
            field=models.EmailField(default='emal@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('cancel', 'Cancel'), ('done', 'Done')], default='pending', max_length=255),
        ),
    ]
