# Generated by Django 4.1.7 on 2023-03-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punishment',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='crimetype',
            table='crimeType',
        ),
        migrations.AlterModelTable(
            name='criminalstatus',
            table='criminalStatus',
        ),
        migrations.AlterModelTable(
            name='punishment',
            table='Punishment',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='userRole',
        ),
    ]
