# Generated by Django 4.1.7 on 2023-03-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crimetype',
            options={'verbose_name': 'Crime Type', 'verbose_name_plural': 'Crime Type List'},
        ),
        migrations.AlterModelOptions(
            name='criminalstatus',
            options={'verbose_name': 'Criminal Status', 'verbose_name_plural': 'Criminal Status List'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'DMP', 'verbose_name_plural': 'DMP List'},
        ),
        migrations.AlterModelOptions(
            name='postion',
            options={'verbose_name': 'Postion', 'verbose_name_plural': 'Postion List'},
        ),
        migrations.AlterModelOptions(
            name='punishment',
            options={'verbose_name': 'Punishment', 'verbose_name_plural': 'Punishment List'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Station', 'verbose_name_plural': 'Station List'},
        ),
    ]
