# Generated by Django 4.1.7 on 2023-04-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_staffaccountprofile_district'),
        ('settings', '0002_alter_crimetype_options_alter_criminalstatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='District',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
