# Generated by Django 4.1.7 on 2023-03-20 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_postion'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Upazila',
                'verbose_name_plural': 'Upazilas',
            },
        ),
        migrations.AddField(
            model_name='station',
            name='upazila',
            field=models.CharField(default=datetime.datetime(2023, 3, 20, 15, 28, 56, 515311, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
