# Generated by Django 4.1.7 on 2023-03-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_delete_upazila_rename_upazila_station_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.district'),
        ),
    ]
