# Generated by Django 4.1.7 on 2023-03-21 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_userrole_options_alter_userrole_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 3, 21, 9, 27, 44, 256533, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
