# Generated by Django 4.1.7 on 2023-03-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_groups'),
        ('settings', '0009_userrole_create_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
