# Generated by Django 4.1.7 on 2023-03-21 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_delete_userrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crimetype',
            options={'verbose_name': 'Crime Type', 'verbose_name_plural': 'Crime Types'},
        ),
        migrations.AlterModelOptions(
            name='criminalstatus',
            options={'verbose_name': 'Criminal Status', 'verbose_name_plural': 'Criminal Status'},
        ),
        migrations.AlterModelOptions(
            name='postion',
            options={'verbose_name': 'Postion', 'verbose_name_plural': 'Postions'},
        ),
    ]
